version: '3.8'

services:

  app-redis:
    image: redislabs/redismod:latest
    container_name: app-redis
    ports:
      - "6379:6379"
    networks:
      - redis-microservices-network
    restart: always


  app-mysql:
    build:
      context: ./mysql-database
      dockerfile: Dockerfile
    container_name: app-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    networks:
      - redis-microservices-network
    restart: always


networks:
  redis-microservices-network:
    driver: bridge
